version: '3'
services:
  web:
    build:
      context: .  # Dockerfile'ın bulunduğu dizin
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Dış dünyada 8080 portu, Docker içinde 80 portu ile eşleşecek
